name: C++ CI

# 触发工作流的事件
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake  libboost-dev

          python -m pip install --upgrade pip
          pip install -r src/tools/python/requirements.txt

      - name: Configure & Build with CMake
        run: |
          cmake -B build
          cmake --build build

      - name: heap_test
        run: |
          cd build/src/tools && ./writer && ./reader && ./write_heap && ./read_heap && ./simulation_toykit
        
      - name: sweep_test
        run: >
          cd build/src/tools/python &&
          python3 ./sweep_table.py --nominal '[["red", "green", "blue"], ["10+1i", "100-1i"]]' | 
          python3 ./sweep_row.py --cmd "python3 ./sweep_table.py --start 0 --end 1 --size 10 --random_sampling uniform | 
          python3 ./sweep_row.py --cmd echo | python3 ./sweep_row.py --securty_mode 1 --cmd echo"
      
      - name: ipc_spin_lock_test_multithreading
        run: >
          cd build/src/tools && cp ./python/*.py ./ && time python3 ./sweep_table.py --start 0 --end 9 --size 1000 | python3 ./sweep_row.py --cmd "./ipc_spin_lock_test"